# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1056, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1061, 581))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NavigationInterface = NavigationInterface(self.layoutWidget)
        self.NavigationInterface.setStyleSheet("")
        self.NavigationInterface.setObjectName("NavigationInterface")
        self.horizontalLayout.addWidget(self.NavigationInterface)
        self.home = QtWidgets.QWidget(self.layoutWidget)
        self.home.setStyleSheet("QWidget{\n"
"    background:rgb(249, 249, 249)\n"
"}")
        self.home.setObjectName("home")
        self.SimpleCardWidget_4 = SimpleCardWidget(self.home)
        self.SimpleCardWidget_4.setGeometry(QtCore.QRect(0, 0, 1001, 581))
        self.SimpleCardWidget_4.setObjectName("SimpleCardWidget_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.SimpleCardWidget_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 981, 561))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SimpleCardWidget_select = SimpleCardWidget(self.layoutWidget1)
        self.SimpleCardWidget_select.setMaximumSize(QtCore.QSize(280, 16777215))
        self.SimpleCardWidget_select.setObjectName("SimpleCardWidget_select")
        self.layoutWidget2 = QtWidgets.QWidget(self.SimpleCardWidget_select)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 60, 284, 447))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_double_potion_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_double_potion_2.setObjectName("horizontalLayout_double_potion_2")
        self.CheckBox_open_game = CheckBox(self.layoutWidget2)
        self.CheckBox_open_game.setStyleSheet("CheckBox {\n"
"    color: black;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    spacing: 8px;\n"
"    min-width: 28px;\n"
"    min-height: 22px;\n"
"    outline: none;\n"
"    margin-left: 1px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"CheckBox::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"CheckBox::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"CheckBox::indicator:checked,\n"
"CheckBox::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"\n"
"CheckBox::indicator:checked:hover,\n"
"CheckBox::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:pressed,\n"
"CheckBox::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"CheckBox:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"CheckBox::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:disabled,\n"
"CheckBox::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.CheckBox_open_game.setObjectName("CheckBox_open_game")
        self.horizontalLayout_double_potion_2.addWidget(self.CheckBox_open_game)
        self.TransparentToolButton_entry_game = TransparentToolButton(self.layoutWidget2)
        icon = QtGui.QIcon.fromTheme("accessories-calculator")
        self.TransparentToolButton_entry_game.setIcon(icon)
        self.TransparentToolButton_entry_game.setObjectName("TransparentToolButton_entry_game")
        self.horizontalLayout_double_potion_2.addWidget(self.TransparentToolButton_entry_game)
        self.verticalLayout.addLayout(self.horizontalLayout_double_potion_2)
        self.horizontalLayout_double_potion = QtWidgets.QHBoxLayout()
        self.horizontalLayout_double_potion.setObjectName("horizontalLayout_double_potion")
        self.CheckBox_double_potion = CheckBox(self.layoutWidget2)
        self.CheckBox_double_potion.setStyleSheet("CheckBox {\n"
"    color: black;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    spacing: 8px;\n"
"    min-width: 28px;\n"
"    min-height: 22px;\n"
"    outline: none;\n"
"    margin-left: 1px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"CheckBox::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"CheckBox::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"CheckBox::indicator:checked,\n"
"CheckBox::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"\n"
"CheckBox::indicator:checked:hover,\n"
"CheckBox::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:pressed,\n"
"CheckBox::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"CheckBox:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"CheckBox::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:disabled,\n"
"CheckBox::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.CheckBox_double_potion.setObjectName("CheckBox_double_potion")
        self.horizontalLayout_double_potion.addWidget(self.CheckBox_double_potion)
        self.TransparentToolButton_double_potion = TransparentToolButton(self.layoutWidget2)
        self.TransparentToolButton_double_potion.setObjectName("TransparentToolButton_double_potion")
        self.horizontalLayout_double_potion.addWidget(self.TransparentToolButton_double_potion)
        self.verticalLayout.addLayout(self.horizontalLayout_double_potion)
        self.horizontalLayout_shuatili = QtWidgets.QHBoxLayout()
        self.horizontalLayout_shuatili.setObjectName("horizontalLayout_shuatili")
        self.CheckBox_tili = CheckBox(self.layoutWidget2)
        self.CheckBox_tili.setStyleSheet("CheckBox {\n"
"    color: black;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    spacing: 8px;\n"
"    min-width: 28px;\n"
"    min-height: 22px;\n"
"    outline: none;\n"
"    margin-left: 1px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"CheckBox::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"CheckBox::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"CheckBox::indicator:checked,\n"
"CheckBox::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"\n"
"CheckBox::indicator:checked:hover,\n"
"CheckBox::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:pressed,\n"
"CheckBox::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"CheckBox:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"CheckBox::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:disabled,\n"
"CheckBox::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.CheckBox_tili.setObjectName("CheckBox_tili")
        self.horizontalLayout_shuatili.addWidget(self.CheckBox_tili)
        self.TransparentToolButton_tili = TransparentToolButton(self.layoutWidget2)
        self.TransparentToolButton_tili.setObjectName("TransparentToolButton_tili")
        self.horizontalLayout_shuatili.addWidget(self.TransparentToolButton_tili)
        self.verticalLayout.addLayout(self.horizontalLayout_shuatili)
        self.horizontalLayout_reward = QtWidgets.QHBoxLayout()
        self.horizontalLayout_reward.setObjectName("horizontalLayout_reward")
        self.CheckBox_reward = CheckBox(self.layoutWidget2)
        self.CheckBox_reward.setStyleSheet("CheckBox {\n"
"    color: black;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    spacing: 8px;\n"
"    min-width: 28px;\n"
"    min-height: 22px;\n"
"    outline: none;\n"
"    margin-left: 1px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"CheckBox::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"CheckBox::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"CheckBox::indicator:checked,\n"
"CheckBox::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"\n"
"CheckBox::indicator:checked:hover,\n"
"CheckBox::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:pressed,\n"
"CheckBox::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"CheckBox:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"CheckBox::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:disabled,\n"
"CheckBox::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.CheckBox_reward.setObjectName("CheckBox_reward")
        self.horizontalLayout_reward.addWidget(self.CheckBox_reward)
        self.TransparentToolButton_daily = TransparentToolButton(self.layoutWidget2)
        self.TransparentToolButton_daily.setObjectName("TransparentToolButton_daily")
        self.horizontalLayout_reward.addWidget(self.TransparentToolButton_daily)
        self.verticalLayout.addLayout(self.horizontalLayout_reward)
        self.horizontalLayout_stacking_resources = QtWidgets.QHBoxLayout()
        self.horizontalLayout_stacking_resources.setObjectName("horizontalLayout_stacking_resources")
        self.CheckBox_resources = CheckBox(self.layoutWidget2)
        self.CheckBox_resources.setStyleSheet("CheckBox {\n"
"    color: black;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    spacing: 8px;\n"
"    min-width: 28px;\n"
"    min-height: 22px;\n"
"    outline: none;\n"
"    margin-left: 1px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"CheckBox::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"CheckBox::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"CheckBox::indicator:checked,\n"
"CheckBox::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"\n"
"CheckBox::indicator:checked:hover,\n"
"CheckBox::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:pressed,\n"
"CheckBox::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"CheckBox:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"CheckBox::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:disabled,\n"
"CheckBox::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.CheckBox_resources.setObjectName("CheckBox_resources")
        self.horizontalLayout_stacking_resources.addWidget(self.CheckBox_resources)
        self.TransparentToolButton_resources = TransparentToolButton(self.layoutWidget2)
        self.TransparentToolButton_resources.setObjectName("TransparentToolButton_resources")
        self.horizontalLayout_stacking_resources.addWidget(self.TransparentToolButton_resources)
        self.verticalLayout.addLayout(self.horizontalLayout_stacking_resources)
        self.horizontalLayout_stacking_resources_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_stacking_resources_2.setObjectName("horizontalLayout_stacking_resources_2")
        self.CheckBox_exchange = CheckBox(self.layoutWidget2)
        self.CheckBox_exchange.setStyleSheet("CheckBox {\n"
"    color: black;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    spacing: 8px;\n"
"    min-width: 28px;\n"
"    min-height: 22px;\n"
"    outline: none;\n"
"    margin-left: 1px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"CheckBox::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"CheckBox::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"CheckBox::indicator:checked,\n"
"CheckBox::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"\n"
"CheckBox::indicator:checked:hover,\n"
"CheckBox::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:pressed,\n"
"CheckBox::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"CheckBox:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"CheckBox::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:disabled,\n"
"CheckBox::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.CheckBox_exchange.setObjectName("CheckBox_exchange")
        self.horizontalLayout_stacking_resources_2.addWidget(self.CheckBox_exchange)
        self.TransparentToolButton_exchange = TransparentToolButton(self.layoutWidget2)
        self.TransparentToolButton_exchange.setObjectName("TransparentToolButton_exchange")
        self.horizontalLayout_stacking_resources_2.addWidget(self.TransparentToolButton_exchange)
        self.verticalLayout.addLayout(self.horizontalLayout_stacking_resources_2)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_btn = QtWidgets.QHBoxLayout()
        self.horizontalLayout_btn.setObjectName("horizontalLayout_btn")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_btn.addItem(spacerItem1)
        self.PushButton_select_all = PushButton(self.layoutWidget2)
        self.PushButton_select_all.setObjectName("PushButton_select_all")
        self.horizontalLayout_btn.addWidget(self.PushButton_select_all)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_btn.addItem(spacerItem2)
        self.PushButton_clean_all = PushButton(self.layoutWidget2)
        self.PushButton_clean_all.setObjectName("PushButton_clean_all")
        self.horizontalLayout_btn.addWidget(self.PushButton_clean_all)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_btn.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_btn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.BodyLabel = BodyLabel(self.layoutWidget2)
        self.BodyLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.BodyLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout_3.addWidget(self.BodyLabel)
        self.ComboBox_after_finish = ComboBox(self.layoutWidget2)
        self.ComboBox_after_finish.setMinimumSize(QtCore.QSize(275, 0))
        self.ComboBox_after_finish.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ComboBox_after_finish.setObjectName("ComboBox_after_finish")
        self.verticalLayout_3.addWidget(self.ComboBox_after_finish, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_btn_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_btn_2.setObjectName("horizontalLayout_btn_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_btn_2.addItem(spacerItem6)
        self.PushButton_stop = PushButton(self.layoutWidget2)
        self.PushButton_stop.setObjectName("PushButton_stop")
        self.horizontalLayout_btn_2.addWidget(self.PushButton_stop)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_btn_2.addItem(spacerItem7)
        self.PushButton_start = PushButton(self.layoutWidget2)
        self.PushButton_start.setObjectName("PushButton_start")
        self.horizontalLayout_btn_2.addWidget(self.PushButton_start)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_btn_2.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_btn_2)
        self.StrongBodyLabel = StrongBodyLabel(self.SimpleCardWidget_select)
        self.StrongBodyLabel.setGeometry(QtCore.QRect(10, 20, 111, 19))
        self.StrongBodyLabel.setStyleSheet("background-color: transparent;")
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.horizontalLayout_2.addWidget(self.SimpleCardWidget_select)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SimpleCardWidget_5 = SimpleCardWidget(self.layoutWidget1)
        self.SimpleCardWidget_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SimpleCardWidget_5.setObjectName("SimpleCardWidget_5")
        self.frame_daily = QtWidgets.QFrame(self.SimpleCardWidget_5)
        self.frame_daily.setGeometry(QtCore.QRect(50, 40, 211, 151))
        self.frame_daily.setStyleSheet("background-color: transparent;")
        self.frame_daily.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_daily.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_daily.setObjectName("frame_daily")
        self.widget = QtWidgets.QWidget(self.frame_daily)
        self.widget.setGeometry(QtCore.QRect(10, 10, 191, 136))
        self.widget.setObjectName("widget")
        self.verticalLayout_daily = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_daily.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_daily.setObjectName("verticalLayout_daily")
        self.CheckBox_market = CheckBox(self.widget)
        self.CheckBox_market.setStyleSheet("CheckBox {\n"
"    color: black;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    spacing: 8px;\n"
"    min-width: 28px;\n"
"    min-height: 22px;\n"
"    outline: none;\n"
"    margin-left: 1px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"CheckBox::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"CheckBox::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"CheckBox::indicator:checked,\n"
"CheckBox::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"\n"
"CheckBox::indicator:checked:hover,\n"
"CheckBox::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:pressed,\n"
"CheckBox::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"CheckBox:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"CheckBox::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:disabled,\n"
"CheckBox::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.CheckBox_market.setObjectName("CheckBox_market")
        self.verticalLayout_daily.addWidget(self.CheckBox_market)
        self.CheckBox_fleet = CheckBox(self.widget)
        self.CheckBox_fleet.setStyleSheet("CheckBox {\n"
"    color: black;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    spacing: 8px;\n"
"    min-width: 28px;\n"
"    min-height: 22px;\n"
"    outline: none;\n"
"    margin-left: 1px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"CheckBox::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"CheckBox::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"CheckBox::indicator:checked,\n"
"CheckBox::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"\n"
"CheckBox::indicator:checked:hover,\n"
"CheckBox::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:pressed,\n"
"CheckBox::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"CheckBox:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"CheckBox::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:disabled,\n"
"CheckBox::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.CheckBox_fleet.setObjectName("CheckBox_fleet")
        self.verticalLayout_daily.addWidget(self.CheckBox_fleet)
        self.CheckBox_receive_mail = CheckBox(self.widget)
        self.CheckBox_receive_mail.setStyleSheet("CheckBox {\n"
"    color: black;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    spacing: 8px;\n"
"    min-width: 28px;\n"
"    min-height: 22px;\n"
"    outline: none;\n"
"    margin-left: 1px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"CheckBox::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"CheckBox::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"CheckBox::indicator:checked,\n"
"CheckBox::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"\n"
"CheckBox::indicator:checked:hover,\n"
"CheckBox::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:pressed,\n"
"CheckBox::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"CheckBox:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"CheckBox::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:disabled,\n"
"CheckBox::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.CheckBox_receive_mail.setObjectName("CheckBox_receive_mail")
        self.verticalLayout_daily.addWidget(self.CheckBox_receive_mail)
        self.CheckBox_gift_of_shana = CheckBox(self.widget)
        self.CheckBox_gift_of_shana.setStyleSheet("CheckBox {\n"
"    color: black;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    spacing: 8px;\n"
"    min-width: 28px;\n"
"    min-height: 22px;\n"
"    outline: none;\n"
"    margin-left: 1px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"CheckBox::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"CheckBox::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"CheckBox::indicator:checked,\n"
"CheckBox::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"\n"
"CheckBox::indicator:checked:hover,\n"
"CheckBox::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:pressed,\n"
"CheckBox::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"CheckBox:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"CheckBox::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:disabled,\n"
"CheckBox::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.CheckBox_gift_of_shana.setObjectName("CheckBox_gift_of_shana")
        self.verticalLayout_daily.addWidget(self.CheckBox_gift_of_shana)
        self.CheckBox_online_gift = CheckBox(self.widget)
        self.CheckBox_online_gift.setStyleSheet("CheckBox {\n"
"    color: black;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    spacing: 8px;\n"
"    min-width: 28px;\n"
"    min-height: 22px;\n"
"    outline: none;\n"
"    margin-left: 1px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"CheckBox::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"CheckBox::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"CheckBox::indicator:checked,\n"
"CheckBox::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"\n"
"CheckBox::indicator:checked:hover,\n"
"CheckBox::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:pressed,\n"
"CheckBox::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"CheckBox:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"CheckBox::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:disabled,\n"
"CheckBox::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.CheckBox_online_gift.setObjectName("CheckBox_online_gift")
        self.verticalLayout_daily.addWidget(self.CheckBox_online_gift)
        self.frame_tili = QtWidgets.QFrame(self.SimpleCardWidget_5)
        self.frame_tili.setEnabled(True)
        self.frame_tili.setGeometry(QtCore.QRect(50, 40, 221, 161))
        self.frame_tili.setAutoFillBackground(False)
        self.frame_tili.setStyleSheet("background-color: transparent;")
        self.frame_tili.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tili.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tili.setObjectName("frame_tili")
        self.widget1 = QtWidgets.QWidget(self.frame_tili)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 192, 138))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_tili = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_tili.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_tili.setObjectName("verticalLayout_tili")
        self.SegmentedWidget_2 = SegmentedWidget(self.widget1)
        self.SegmentedWidget_2.setObjectName("SegmentedWidget_2")
        self.verticalLayout_tili.addWidget(self.SegmentedWidget_2)
        self.CheckBox_13 = CheckBox(self.widget1)
        self.CheckBox_13.setStyleSheet("CheckBox {\n"
"    color: black;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    spacing: 8px;\n"
"    min-width: 28px;\n"
"    min-height: 22px;\n"
"    outline: none;\n"
"    margin-left: 1px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"CheckBox::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"CheckBox::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"CheckBox::indicator:checked,\n"
"CheckBox::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"\n"
"CheckBox::indicator:checked:hover,\n"
"CheckBox::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:pressed,\n"
"CheckBox::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"CheckBox:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"CheckBox::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:disabled,\n"
"CheckBox::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.CheckBox_13.setObjectName("CheckBox_13")
        self.verticalLayout_tili.addWidget(self.CheckBox_13)
        self.CheckBox_14 = CheckBox(self.widget1)
        self.CheckBox_14.setStyleSheet("CheckBox {\n"
"    color: black;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    spacing: 8px;\n"
"    min-width: 28px;\n"
"    min-height: 22px;\n"
"    outline: none;\n"
"    margin-left: 1px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"CheckBox::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"CheckBox::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"CheckBox::indicator:checked,\n"
"CheckBox::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"\n"
"CheckBox::indicator:checked:hover,\n"
"CheckBox::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:pressed,\n"
"CheckBox::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"CheckBox:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"CheckBox::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:disabled,\n"
"CheckBox::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.CheckBox_14.setObjectName("CheckBox_14")
        self.verticalLayout_tili.addWidget(self.CheckBox_14)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.BodyLabel_characters_number = BodyLabel(self.widget1)
        self.BodyLabel_characters_number.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.BodyLabel_characters_number.setObjectName("BodyLabel_characters_number")
        self.horizontalLayout_5.addWidget(self.BodyLabel_characters_number)
        self.SpinBox_2 = SpinBox(self.widget1)
        self.SpinBox_2.setMinimum(1)
        self.SpinBox_2.setMaximum(8)
        self.SpinBox_2.setProperty("value", 6)
        self.SpinBox_2.setObjectName("SpinBox_2")
        self.horizontalLayout_5.addWidget(self.SpinBox_2)
        self.verticalLayout_tili.addLayout(self.horizontalLayout_5)
        self.frame_tili.raise_()
        self.CheckBox_13.raise_()
        self.CheckBox_14.raise_()
        self.SegmentedWidget_2.raise_()
        self.CheckBox_market.raise_()
        self.CheckBox_fleet.raise_()
        self.CheckBox_receive_mail.raise_()
        self.CheckBox_gift_of_shana.raise_()
        self.frame_daily.raise_()
        self.verticalLayout_2.addWidget(self.SimpleCardWidget_5)
        self.SimpleCardWidget_6 = SimpleCardWidget(self.layoutWidget1)
        self.SimpleCardWidget_6.setMaximumSize(QtCore.QSize(16777215, 150))
        self.SimpleCardWidget_6.setObjectName("SimpleCardWidget_6")
        self.BodyLabel_tip = BodyLabel(self.SimpleCardWidget_6)
        self.BodyLabel_tip.setGeometry(QtCore.QRect(10, 10, 63, 19))
        self.BodyLabel_tip.setStyleSheet("background-color: transparent;")
        self.BodyLabel_tip.setObjectName("BodyLabel_tip")
        self.verticalLayout_2.addWidget(self.SimpleCardWidget_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.SimpleCardWidget_message = SimpleCardWidget(self.layoutWidget1)
        self.SimpleCardWidget_message.setObjectName("SimpleCardWidget_message")
        self.SmoothScrollArea = SmoothScrollArea(self.SimpleCardWidget_message)
        self.SmoothScrollArea.setGeometry(QtCore.QRect(10, 50, 341, 491))
        self.SmoothScrollArea.setStyleSheet("background-color: transparent;\n"
"border:none;")
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 341, 491))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.plainTextEdit_log = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEdit_log.setGeometry(QtCore.QRect(3, 0, 331, 491))
        self.plainTextEdit_log.setObjectName("plainTextEdit_log")
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.StrongBodyLabel_2 = StrongBodyLabel(self.SimpleCardWidget_message)
        self.StrongBodyLabel_2.setGeometry(QtCore.QRect(20, 20, 111, 19))
        self.StrongBodyLabel_2.setStyleSheet("background-color: transparent;")
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.horizontalLayout_2.addWidget(self.SimpleCardWidget_message)
        self.horizontalLayout.addWidget(self.home)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1056, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CheckBox_open_game.setText(_translate("MainWindow", "进入游戏"))
        self.CheckBox_double_potion.setText(_translate("MainWindow", "做双倍药水"))
        self.CheckBox_tili.setText(_translate("MainWindow", "刷体力"))
        self.CheckBox_reward.setText(_translate("MainWindow", "完成日常"))
        self.CheckBox_resources.setText(_translate("MainWindow", "叠加资源"))
        self.CheckBox_exchange.setText(_translate("MainWindow", "商人信用兑换"))
        self.PushButton_select_all.setText(_translate("MainWindow", "全选"))
        self.PushButton_clean_all.setText(_translate("MainWindow", "清除"))
        self.BodyLabel.setText(_translate("MainWindow", "完成后执行："))
        self.PushButton_stop.setText(_translate("MainWindow", "停止"))
        self.PushButton_start.setText(_translate("MainWindow", "开始"))
        self.StrongBodyLabel.setText(_translate("MainWindow", "选择功能"))
        self.CheckBox_market.setText(_translate("MainWindow", "领取商城每日奖励"))
        self.CheckBox_fleet.setText(_translate("MainWindow", "舰队日常"))
        self.CheckBox_receive_mail.setText(_translate("MainWindow", "领取邮件"))
        self.CheckBox_gift_of_shana.setText(_translate("MainWindow", "签到并抽取夏娜的赠礼"))
        self.CheckBox_online_gift.setText(_translate("MainWindow", "领取在线礼物"))
        self.CheckBox_13.setText(_translate("MainWindow", "设置1"))
        self.CheckBox_14.setText(_translate("MainWindow", "设置2"))
        self.BodyLabel_characters_number.setText(_translate("MainWindow", "角色数量"))
        self.BodyLabel_tip.setText(_translate("MainWindow", "提示"))
        self.StrongBodyLabel_2.setText(_translate("MainWindow", "当前消息"))
from qfluentwidgets import BodyLabel, CheckBox, ComboBox, NavigationInterface, PushButton, SegmentedWidget, SimpleCardWidget, SmoothScrollArea, SpinBox, StrongBodyLabel, TransparentToolButton
